Models/ErrorViewModel.cs
namespace DemoGDMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/BaoGiaController.cs
using DemoGDMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace DemoGDMVC.Controllers
{
    public class BaoGiaController : Controller
    {
        private readonly ILogger<BaoGiaController> _logger;

        public BaoGiaController(ILogger<BaoGiaController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ChiTietBaoGia()
        {
            return View();
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/CongNoController.cs
using DemoGDMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace DemoGDMVC.Controllers
{
    public class CongNoController : Controller
    {
        private readonly ILogger<CongNoController> _logger;

        public CongNoController(ILogger<CongNoController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ChiTietCN()
        {
            return View();
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/GiaoHangController.cs
using DemoGDMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace DemoGDMVC.Controllers
{
    public class GiaoHangController : Controller
    {
        private readonly ILogger<GiaoHangController> _logger;

        public GiaoHangController(ILogger<GiaoHangController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ChiTietDon()
        {
            return View();
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/HomeController.cs
using DemoGDMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace DemoGDMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ChiTietDon()
        {
            return View();
        }

        

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;

namespace DemoGDMVC.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Login()
        {
            return View();
        }
    }
}

Controllers/ThongKeTaiController.cs
using DemoGDMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace DemoGDMVC.Controllers
{
    public class ThongKeTaiController : Controller
    {
        private readonly ILogger<ThongKeTaiController> _logger;

        public ThongKeTaiController(ILogger<ThongKeTaiController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ChiTietTai()
        {
            return View();
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/TonKhoController.cs
using DemoGDMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace DemoGDMVC.Controllers
{
    public class TonKhoController : Controller
    {
        private readonly ILogger<TonKhoController> _logger;

        public TonKhoController(ILogger<TonKhoController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/BaoGia/ChiTietBaoGia.cshtml
@{
    ViewData["Title"] = "Báo giá  chi tiết";
}

<head>
    <link rel="stylesheet" href="~/css/BaoGiaChiTiet.css" />
</head>

<h2 class="text-center mb-4">Chi tiết báo giá</h2>
<div class="">
    <div class="">
        <div> <label>Khách Hàng: CTY 01</label></div>
        <div class="">
            <label class="col"> Ngày áp dụng: 20-08-2024</label>
        </div>
        <div class="">
            <label class="col">Phụ trách: Lê Khác Hòa</label>
        </div>
    </div>
</div>

<div class="table-responsive">
    <table id="quotationTable" class="table table-bordered table-hover">
        <thead class="table-light">
            <tr>
                <th class="fixed-column">STT</th>
                <th class="fixed-column-2">Tên hàng</th>
                <th>Quy cách</th>
                <th>Đơn vị</th>
                <th>Đơn giá</th>
                <th>Đơn giá cũ</th>
                <th>Ghi chú</th>
            </tr>
        </thead>
        <tbody id="tableBody">
        </tbody>
    </table>
</div>
<!-- Phân trang -->
<div class="row mb-3">
    <div class="justify-content-between col-6" style="margin-top: 2px;">
        <div class="d-flex align-items-center">
            <label class="" for="rowsPerPage">Số dòng:</label>
            <select id="rowsPerPage" class="form-select" style="width: 50%;" onchange="changeRowsPerPage()">
                <option value="20">20</option>
                <option value="50">50</option>
                <option value="50">100</option>
            </select>
        </div>
    </div>
    <div id="pagination" class="pagination col-6"></div>
</div>

<div class="d-flex justify-content-center mt-1 ">
    <button class="btn btn-primary" onclick="window.location.href='/BaoGia'">
        Back
    </button>
</div>

<script src="~/js/BaoGiaChiTiet.js"></script>

Views/BaoGia/Index.cshtml
@{
    ViewData["Title"] = "Báo giá";
}

<head>
    <link rel="stylesheet" href="~/css/BaoGia.css" />
</head>

<h2 class="text-center mb-4">Báo giá</h2>
<div class="mb-3">
    <input type="text" id="searchInput" class="form-control" onkeyup="searchFunction()" placeholder="Tìm kiếm theo khách hàng">
</div>

<table id="quotationTable" class="table table-bordered table-hover">
    <thead class="table-light">
        <tr>
            <th>Khách hàng</th>
            <th>Số phiếu</th>
            <th>Ngày áp dụng</th>
            <th>Phụ trách</th>
        </tr>
    </thead>
    <tbody id="tableBody">
    </tbody>
</table>
<!-- Phân trang -->
<div class="row mb-3">
    <div class="justify-content-between col-6" style="margin-top: 2px;">
        <div class="d-flex align-items-center">
            <label class="" for="rowsPerPage">Số dòng:</label>
            <select id="rowsPerPage" class="form-select" style="width: 50%;" onchange="changeRowsPerPage()">
                <option value="20">20</option>
                <option value="50">50</option>
                <option value="50">100</option>
            </select>
        </div>
    </div>
    <div id="pagination" class="pagination col-6"></div>
</div>

<div class="d-flex justify-content-center mt-1">
    <button class="btn btn-primary" onclick="window.location.href='/Home'">
        Back
    </button>
</div>

<script src="~/js/BaoGia.js"></script>

Views/CongNo/ChiTietCN.cshtml
@{
    ViewData["Title"] = "Công nợ chi tiết";
}

<head>
    <link rel="stylesheet" href="~/css/ChiTietCN.css" />
</head>

<h2 class="text-center mb-4">Chi tiết công nợ</h2>
<div class="">
    <div class="">
        <div><label>Khách hàng: CTY 01</label></div>
        <div>
            <label class="">Phụ trách: Lê Khắc Hòa</label>
        </div>
        <div class="row" style="height: 28px;">

            <label class="col-6">Nợ hiện tại: </label>
            <label class="col-6">Hạn TT: 60</label>
        </div>
        <div>
            <label>Nợ quá hạn:</label>
        </div>
        <div class="justify-content-between mb-3">
            <div class="d-flex align-items-center">
                <label class="" for="rowsPerPage" style="width: 30%;">Năm:</label>
                <select id="warehouseSelect" class="form-select" style="width: 50%;">
                    <option value="DC Thanh Pham" selected>2022</option>
                    <option value="DC Nguyen Lieu">2022</option>
                    <option value="DC May Moc">2021</option>
                    <option value="DC Phu Tung">2024</option>
                </select>
            </div>
        </div>

    </div>
</div>
<ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item" role="presentation">
        <button style="font-size: 14px;" class="nav-link active" id="quotation-tab" data-bs-toggle="tab" data-bs-target="#quotationTableContainer" type="button" role="tab" aria-controls="quotationTableContainer" aria-selected="true">Chi Tiết</button>
    </li>
    <li class="nav-item" role="presentation">
        <button style="font-size: 14px;" class="nav-link" id="pending-tab" data-bs-toggle="tab" data-bs-target="#pendingPaymentsContainer" type="button" role="tab" aria-controls="pendingPaymentsContainer" aria-selected="false">Chưa Thanh Toán</button>
    </li>
</ul>
<div class="tab-content " id="myTabContent">
    <div class="tab-pane fade show active" id="quotationTableContainer" role="tabpanel" aria-labelledby="quotation-tab">

        <table id="quotationTable" class="table table-bordered table-hover">
            <thead class="table-light">
                <tr>
                    <th>Tháng</th>
                    <th>Nợ phát sinh</th>
                    <th>Đã thanh toán</th>
                    <th>Còn lại</th>
                </tr>
            </thead>
            <tbody>
                <script>
                    for (let i = 1; i <= 12; i++) {
                        document.write(`
                                                        <tr>
                                                            <td>${i}</td>
                                                            <td></td>
                                                            <td></td>
                                                            <td></td>
                                                        </tr>
                                                    `);
                    }
                </script>
            </tbody>
        </table>
    </div>
    <div class="tab-pane fade" id="pendingPaymentsContainer" role="tabpanel" aria-labelledby="pending-tab">

        <div class="table-responsive">
            <table class="table table-bordered table-hover">
                <thead class="table-light">
                    <tr>
                        <th class="fixed-column">Tháng</th>
                        <th class="fixed-column-2">Ngày phát sinh</th>
                        <th>Số hóa đơn</th>
                        <th>Số tiền</th>
                        <th>Đã thu</th>
                        <th>Còn lại</th>
                    </tr>
                </thead>
                <tbody id="tableBody">
                    <!-- Nội dung bảng sẽ được load qua JS -->
                </tbody>
            </table>
        </div>

    </div>
</div>
<div class="d-flex justify-content-center mt-1">
    <button class="btn btn-primary" onclick="window.location.href='/CongNo'">
        Back
    </button>
</div>
<script src="~/js/ChiTietCN.js"></script>

Views/CongNo/Index.cshtml
@{
    ViewData["Title"] = "Công nợ";
}

<head>
    <link rel="stylesheet" href="~/css/CongNo.css" />
</head>

<h2 class="text-center mb-4">Công Nợ</h2>
<div class="mb-3">
    <input type="text" id="searchInput" class="form-control" onkeyup="searchFunction()" placeholder="Tìm kiếm theo khách hàng">
</div>

<div class="table-responsive">
    <table id="quotationTable" class="table table-bordered table-hover" style="padding: 5px;">
        <thead class="table-light">
            <tr>
                <th class="fixed-column">Khách hàng</th>
                <th class="fixed-column-2">Nợ hiện tại</th>
                <th>Hạn CN</th>
                <th>Nợ quá hạn</th>
                <th>Ngày đến hạn</th>
                <th>TT trong kỳ</th>
                <th>Ngày thanh toán</th>
                <th>Tổng giao hàng</th>
                <th>Chưa đối chiếu</th>
                <th>Phụ trách</th>
                <th>Công nợ</th>
            </tr>
        </thead>
        <tbody id="tableBody">
            <!-- Nội dung bảng sẽ được load qua JS -->
        </tbody>
    </table>
</div>
<!-- Phân trang -->
<div class="row mb-3">
    <div class="justify-content-between col-6" style="margin-top: 2px;">
        <div class="d-flex align-items-center">
            <label class="" for="rowsPerPage">Số dòng:</label>
            <select id="rowsPerPage" class="form-select" style="width: 50%;" onchange="changeRowsPerPage()">
                <option value="20">20</option>
                <option value="50">50</option>
                <option value="50">100</option>
            </select>
        </div>
    </div>
    <div id="pagination" class="pagination col-6"></div>
</div>

<div class="d-flex justify-content-center mt-1">
    <button class="btn btn-primary" onclick="window.location.href='/Home'">
        Back
    </button>
</div>

<script src="~/js/CongNo.js"></script>

Views/GiaoHang/ChiTietDon.cshtml
@{
    ViewData["Title"] = "Phiếu Giao Hàng";
}

<head>
    <link rel="stylesheet" href="~/css/ChiTietDon.css" />
</head>
<h2 class="text-center mb-4">Phiếu giao hàng</h2>
<div class="mb-3">
    <div class="row">
        <div> <label>Khách Hàng:萬盛（越南）责任有限公司: CTY TNHH  HÀO TRUNG KIỆT (VẠN THỊNH)</label></div>
        <div class="row" style="height: 28px;">
            <label class="col-6"> Ngày giao: 20-08-2024</label>
            <label class="col-6" style="padding: 0;">Số phiếu: BG240801-01</label>
        </div>
        <div class="row" style="height: 28px;">
            <label class="col-6"> Trị giá:</label>
            <label class="col-6" style="padding: 0;">PO#: </label>
        </div>
        <div class="row" style="height: 28px;">
            <label class="col-6"> VAT:</label>
            <label class="col-6" style="padding: 0;">Thành tiền:</label>
        </div>
    </div>
</div>
<!-- <div class="justify-content-between mb-3">
    <div class="d-flex align-items-center">
        <label class="me-3" for="rowsPerPage">Số dòng:</label>
        <select id="rowsPerPage" class="form-select" style="width: 30%;" onchange="changeRowsPerPage()">
            <option value="10">10</option>
            <option value="20">20</option>
            <option value="50">50</option>
        </select>
    </div>
</div> -->
<div class="table-responsive">
    <table id="quotationTable" class="table table-bordered table-hover">
        <thead class="table-light">
            <tr>
                <th class="fixed-column">Tên hàng</th>
                <th class="fixed-column-2">Quy cách</th>
                <th>Số lượng</th>
                <th>Đơn vị</th>
                <th>Đơn giá</th>
                <th>Trị giá</th>
                <th>Trị giá VAT</th>
                <th>Thành tiền</th>
                <th>TL (N.W)</th>
                <th class="fixed-column-2">Ghi chú</th>
            </tr>
        </thead>
        <tbody id="tableBody">
        </tbody>
    </table>
</div>
<div class="d-flex justify-content-center mt-1">
    <button class="btn btn-primary" onclick="window.location.href='/GiaoHang'">
        Back
    </button>
</div>

<script src="~/js/ChiTietDon.js"></script>

Views/GiaoHang/Index.cshtml
@{
    ViewData["Title"] = "Giao hàng";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<head>
    <link rel="stylesheet" href="~/css/ChiTietGiaoHang.css" />
</head>

<h2 class="text-center mb-4">Giao hàng</h2>
<div class="mb-3">
    <input type="text" id="searchInput" class="form-control" onkeyup="searchFunction()" placeholder="Tìm kiếm theo khách hàng/ tên hàng">
</div>
<div class="mb-3">
    <div class="align-items-center">
        <div class="d-flex align-items-center">
            <label for="startDate" class="me-2">Từ ngày:</label>
            <input type="date" id="startDate" class="form-control">
        </div>
    </div>
    <div class="align-items-center mt-3">
        <div class="d-flex align-items-center">
            <label for="endDate" class="me-2">Tới ngày:</label>
            <input type="date" id="endDate" class="form-control">
        </div>
    </div>
</div>


<div class="table-responsive">
    <table id="quotationTable" class="table table-bordered table-hover">
        <thead class="table-light">
            <tr>
                <th class="fixed-column">Khách hàng</th>
                <th class="fixed-column-2">Ngày giao</th>
                <th class="fixed-column-2">Số phiếu</th>
                <th class="fixed-column-2">Số PO</th>
                <th class="fixed-column-2">CN</th>
                <th class="fixed-column-2">Trị giá</th>
                <th class="fixed-column-2">Trị giá VAT</th>
                <th class="fixed-column-2">Thành tiền</th>
                <th class="fixed-column-2">Ghi chú</th>
            </tr>
        </thead>
        <tbody id="tableBody">
            <!-- Nội dung bảng sẽ được load qua JS -->
        </tbody>
    </table>
</div>

<!-- Phân trang -->
<div class="row mb-3" style="margin-top: 5px;">
    <div class="justify-content-between col-6">
        <div class="d-flex align-items-center">
            <label class="" for="rowsPerPage">Số dòng:</label>
            <select id="rowsPerPage" class="form-select" style="width: 50%;" onchange="changeRowsPerPage()">
                <option value="20">20</option>
                <option value="50">50</option>
                <option value="50">100</option>
            </select>
        </div>
    </div>
    <div id="pagination" class="pagination col-6"></div>
</div>
<div class="d-flex justify-content-center mt-1">
    <button class="btn btn-primary" onclick="window.location.href='/Home'">
        Back
    </button>
</div>

<script src="~/js/ChiTietGiaoHang.js"></script>

Views/Home/ChiTietDon.cshtml
@{
    ViewData["Title"] = "Phiếu Giao Hàng";
}

<head>
    <link rel="stylesheet" href="~/css/ChiTietDon.css" />
</head>
<h2 class="text-center mb-4">Phiếu giao hàng</h2>
<div class="mb-3">
    <div class="row">
        <div> <label>Khách Hàng:萬盛（越南）责任有限公司: CTY TNHH  HÀO TRUNG KIỆT (VẠN THỊNH)</label></div>
        <div class="row" style="height: 28px;">
            <label class="col-6"> Ngày giao: 20-08-2024</label>
            <label class="col-6" style="padding: 0;">Số phiếu: BG240801-01</label>
        </div>
        <div class="row" style="height: 28px;">
            <label class="col-6"> Trị giá:</label>
            <label class="col-6" style="padding: 0;">PO#: </label>
        </div>
        <div class="row" style="height: 28px;">
            <label class="col-6"> VAT:</label>
            <label class="col-6" style="padding: 0;">Thành tiền:</label>
        </div>
    </div>
</div>
<!-- <div class="justify-content-between mb-3">
    <div class="d-flex align-items-center">
        <label class="me-3" for="rowsPerPage">Số dòng:</label>
        <select id="rowsPerPage" class="form-select" style="width: 30%;" onchange="changeRowsPerPage()">
            <option value="10">10</option>
            <option value="20">20</option>
            <option value="50">50</option>
        </select>
    </div>
</div> -->
<div class="table-responsive">
    <table id="quotationTable" class="table table-bordered table-hover">
        <thead class="table-light">
            <tr>
                <th class="fixed-column">Tên hàng</th>
                <th class="fixed-column-2">Quy cách</th>
                <th>Số lượng</th>
                <th>Đơn vị</th>
                <th>Đơn giá</th>
                <th>Trị giá</th>
                <th>Trị giá VAT</th>
                <th>Thành tiền</th>
                <th>TL (N.W)</th>
                <th class="fixed-column-2">Ghi chú</th>
            </tr>
        </thead>
        <tbody id="tableBody">
        </tbody>
    </table>
</div>

<script src="~/js/ChiTietDon.js"></script>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Giao hàng";
    Layout = "~/Views/Shared/_Layout.cshtml";
    
}
<head>
    <link rel="stylesheet" href="~/css/Home.css" />
</head>

<div class="d-flex justify-content-center mt-5">
    <h1>Welcome</h1>
</div>
<div class="d-flex justify-content-center mt-5 tex">
    <ul class="list-group d-flex justify-content-center" style="width:100%; text-align:center">
        <li class="list-group-item active" aria-current="true">
            <a class="nav-link" asp-area="" asp-controller="GiaoHang" asp-action="Index">Giao hàng</a>
        </li>
        <li class="list-group-item">
            <a class="nav-link" asp-area="" asp-controller="BaoGia" asp-action="Index">Báo giá</a>
        </li>
        <li class="list-group-item">
            <a class="nav-link" asp-area="" asp-controller="TonKho" asp-action="Index">Tồn Kho</a>
        </li>
        <li class="list-group-item">
            <a class="nav-link" asp-area="" asp-controller="ThongKeTai" asp-action="Index">Thống kê tải</a>
        </li>
        <li class="list-group-item">
            <a class="nav-link" asp-area="" asp-controller="CongNo" asp-action="Index">Công nợ</a>
        </li>
    </ul>
</div>

<script src="~/js/auth.js"></script>

Views/Login/Login.cshtml
@{
    ViewData["Title"] = "Giao hàng";
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";

}

<head>
    <link rel="stylesheet" href="~/css/Login.css" />
</head>

<form action="" class="login-form">
    <div class="login-body">

        <div class="login-left">
            <img class="login-img" src="https://free.vector6.com/wp-content/uploads/2020/12/giang-sinh-noel-vector-069.jpg" alt="">
        </div>

        <div class="login-right">

            <!-- <div class="login-logo">
              <a href=""><img class="logo" src="https://png.pngtree.com/png-clipart/20190611/original/pngtree-wolf-logo-png-image_2306634.jpg" alt=""></a>
            </div> -->

            <div class="login-content">

                <div class="login-title">
                    <span>Đăng nhập</span>
                </div>

                <div class="login-text">
                    <span>Chào mừng trở lại!</span>
                </div>

                <div class="login-input">
                    <div class="login-email">
                        <label for="">Tài khoản</label>
                        <input type="text" id="UserName" placeholder="Tài khoản" />
                    </div>
                    <div class="login-password">
                        <label for="">Mật khẩu</label>
                        <input type="password" id="Password" placeholder="Mật khẩu" />
                    </div>
                </div>
            </div>
            <div class="login-btn">
                <button type="button" id="loginButton">Đăng nhập</button>
            </div>
        </div>

    </div>
</form>

<script src="~/js/Login.js"></script>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DemoGDMVC</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DemoGDMVC.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
</head>
<body>
    <header>
       @*  <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DemoGDMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav> *@
        <nav class="navbar navbar-expand-lg navbar-dark">
            <div class="container-fluid">
                <!-- <a class="navbar-brand" href="#">Logo</a> -->
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-auto justify-content-center">
                        <li class="nav-item">
                            <a class="nav-link active" asp-area="" asp-controller="GiaoHang" asp-action="Index">Giao hàng</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="BaoGia" asp-action="Index">Báo giá</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="TonKho" asp-action="Index">Tồn Kho</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="ThongKeTai" asp-action="Index">Thống kê tải</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="CongNo" asp-action="Index">Công nợ</a>
                        </li>
                    </ul>
                    <div class="navbar-icons">
                        <i class="fas fa-search icon"></i>
                        <i class="fas fa-user-circle icon"></i>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @* <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - DemoGDMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer> *@
    <script src="~/js/auth.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
</head>
<body>
    <div class="login-container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
</body>
</html>